### ISSUE TITLE
Request to add preprocessing scripts for TAC2017ADR sets and dictionaries. 

### ISSUE THREAD

**Issue by tutubalinaev** [dmis-lab/BioSyn#1]
Dear authors,

could you please share preprocessing scripts and MedDRA dictionaries for the TAC2017ADR dump? Thank you in advance!

**Comment by mjeensung** [comment]
Hello tutubalinaev

We've just uploaded the preprocessing scripts for the TAC2017ADR dataset and the MedDRA dictionary.
If you face any problem, please let me know.

https://github.com/dmis-lab/BioSyn/tree/master/preprocess#how-to-pre-process-datasets-and-dictionaires

**Comment by tutubalinaev** [comment]
Dear @mjeensung thank you for the scripts, I preprocessed the TAC2017ADR dataset as well as the MedDRA 19.0 files successfully.
