### ISSUE TITLE
Data inaccessible

### ISSUE THREAD

**Issue by Tesla-jiang** [dmis-lab/BioSyn#11]
Thank you for your work. It's been very useful to me
When I access the data: NCbi-Disease, BC5CDR-Disease, bC5CDR-Chemical, the web page will prompt "no preview, the file is in the owner's recycle bin", can you provide other data download methods

**Comment by mjeensung** [comment]
Hi @1172135979 

Thank you for letting us know!

We've just updated the dataset links.
Could you please try the new links?

**Comment by Tesla-jiang** [comment]
Thank you. The data can be downloaded normally. I have started training the model.
