### ISSUE TITLE
Composite identifier predictions meaning

### ISSUE THREAD

**Issue by sanyabt** [dmis-lab/BioSyn#15]
Hi, thank you so much for your work! 

I have a question about the composite predictions from the model - in your [README example](https://github.com/dmis-lab/BioSyn#result), the model predicts multiple identifiers "D001260|208900" in the top 5. Does this mean that the model found both terms to be similar to the mention text based on probabilities or it is providing alternate possible identifiers? Just want to understand what predicting multiple identifiers implies in BioSyn predictions. Thanks!

**Comment by mjeensung** [comment]
Hi @sanyabt 

Thanks for reaching out to us.
We are using the [MEDIC dictionary](https://ctdbase.org/downloads/;jsessionid=A10A03866A4545D6D0B40B03EE5CCF59#alldiseases) for disease.

If you take a look at the site, it provides 'DiseaseID' as well as 'AltDiseaseIDs'.
So, 'D001260|208900' can be interpreted that 'D001260' is a 'DiseaseID' and '208900' is a 'AltDiseaseIDs'.
