### ISSUE TITLE
Apart from "biosyn-ncbi-disease", are there any other pre-trained models available? or one trained on all?

### ISSUE THREAD

**Issue by QaisarRajput** [dmis-lab/BioSyn#2]
I have been trying to compare BioSyn with BERN. But currently for BioSyn only `biosyn-ncbi-disease` pre-trained model is available. 
Although i can train on the other datasets `bc5cdr-disease`, `bc5cdr-chemical` (as you have mentioned and shared the scripts).
But are there any pre-trained version which can be shared which are reported in the paper

**Comment by mjeensung** [comment]
Thank you for your patience.
I just uploaded the pre-trained version you asked.

**biosyn-bc5cdr-disease**
https://drive.google.com/drive/folders/18dD0s9DY5w7zb04D-jVfxY5ZqnEMi7T7?usp=sharing

**biosyn-bc5cdr-chemical**
https://drive.google.com/drive/folders/1wietDDEFDaDh3n7JdzfAqLSC6h_mEO_O?usp=sharing
