### ISSUE TITLE
Request for preprocessing script

### ISSUE THREAD

**Issue by HaseebYounis1** [dmis-lab/BioSyn#3]
Dear Respected Sir, 
I need your preprocessing script. would you please provide me that? i shall be thankful.

Regards, 
Haseeb Younas

**Comment by mjeensung** [comment]
Hi Haseeb

Sure, I'll work on it and let you know.

**Comment by mjeensung** [comment]
Hello, thank you for your patience.

I just uploaded the preprocessing scripts for the NCBI-disease dataset.

For BC5CDR, I'm still working on it, but it can be preprocessed in the almost same way as the NCBI-disease dataset.
