### ISSUE TITLE
Reproducibility of results on the NCBI Disease corpus

### ISSUE THREAD

**Issue by ArnaudFerre** [dmis-lab/BioSyn#5]
Hi,

Thanks to your Git repo, I was able to make 10 runs on the NCBI corpus with BioSyn.
I only did a single parsing of the data, then 10 independent preprocessing + training + prediction.
My results (with your evaluation script) are Acc1=89.89 with a standard deviation of 0.64 (the variability of the results coming almost exclusively from the preprocessing, from Ab3P I guess).

I understand from your article that your Acc1=91.1 result is obtained on a single run, right?
If so, it seems consistent.

If not, would you have an idea where the small difference could come from? (in this case, I could provide my bash commands, but they are basically a copy of the ones in your readme, without any modification of the options)

Kind regards

**Comment by mjeensung** [comment]
Hi, ArnaudFerre

Yes, I obtained the result on a single run.

Best regards

**Comment by arka2010** [comment]
How did you get the results in one run.
Please feel free to demonstrate.

Regards
Arka
