### ISSUE TITLE
What's the role of "class" field in query files?

### ISSUE THREAD

**Issue by amirj** [dmis-lab/BioSyn#7]
In the following example, "SpecificDisease", "Modifier" and "CompositeMention" are playing any role in the algorithm?
```
10441573||444|459||SpecificDisease||ovarian cancers||D010051
10441573||492|498||Modifier||cancer||D009369
10441573||655|683||CompositeMention||breast cancer|ovarian cancer||D001943|D010051
```

**Comment by mjeensung** [comment]
Hi amirj

In BioSyn, only mentions and CUIs are used.
(Please see https://github.com/dmis-lab/BioSyn/blob/ed9dc962e806e4f6c453652f111eb7c01ffaabec/src/biosyn/data_loader.py#L62)

When you construct new query files, you should just fill the class field with any characters like '-'.

**Comment by amirj** [comment]
Thanks :-)
