### ISSUE TITLE
How to calculate score for each prediction?

### ISSUE THREAD

**Issue by amirj** [dmis-lab/BioSyn#8]
Is it possible to find a relevance score for [each prediction in the inference](https://github.com/dmis-lab/BioSyn/blob/ed9dc962e806e4f6c453652f111eb7c01ffaabec/inference.py#L119)?

**Comment by mjeensung** [comment]
Hi amirj

Can you try `hybrid_score_matrix[hybrid_candidate_idxs]`? 
I haven't tried it, but I think this will find the scores of the top 5 predictions.
